# Generated by Django 6.0.3 on 2026-05-01 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_performancereview_delete_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_joining',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
